const HUNGARIAN_WORDS = [
    "alma", "ajtó", "ablak", "asztal", "autó", "állat", "apa", "anya", "arc", "angyal", "arany", "ág", "ágy", "álom", "árnyék", "árok",
    "bab", "babér", "bakbak", "bal", "balta", "banán", "barát", "barka", "barna", "bástya", "bátor", "batyu", "béka", "béke", "bél", "bélyeg",
    "bénító", "bér", "berény", "beszéd", "betű", "bevon", "bicska", "bíró", "bivaly", "blúz", "bob", "bocsi", "bodza", "bogár", "bogyó", "bojt",
    "bokor", "boldog", "bolt", "bolyhos", "bonbon", "bor", "borjú", "bors", "borsó", "bot", "bozont", "bögöly", "bögre", "bölcs", "bőr", "bűn",
    "bűvös", "bükk", "búza", "búcsú", "bútor", "búvó", "bűz", "cafat", "cápa", "cég", "cél", "céna", "cica", "cicus", "cigány", "cihel", "cikk",
    "ciklon", "cimke", "cím", "címke", "cink", "cinóber", "cipő", "ciprus", "citrom", "comb", "cumi", "csalit", "csaló", "csapat", "csárda", "csata",
    "csatlak", "csavar", "csel", "csemege", "csend", "csengő", "csepp", "cser", "csere", "cserép", "csibe", "csiga", "csík", "csillag", "csinos",
    "csípő", "csizma", "csokor", "csoki", "csomó", "csonk", "csont", "csoport", "cső", "csőr", "csúcs", "csúnya", "csúszda", "csütörtök", "cukor",
    "dália", "dal", "darab", "daru", "dátum", "denevér", "derék", "derű", "dés", "deszka", "diák", "dió", "dísz", "dob", "doboz", "dolog", "domb",
    "donga", "dorgál", "daru", "drága", "drót", "duda", "düh", "dugasz", "duna", "durva", "duzzaszt", "ebéd", "ecet", "ecset", "eder", "egér", "ég",
    "égbolt", "égő", "egység", "együtt", "éhes", "ehun", "éj", "éjfél", "éjjel", "ékszer", "eladó", "elég", "elem", "élemed", "élet", "ellen", "ellenség",
    "élmény", "elő", "előtt", "élő", "ember", "emlék", "emse", "enek", "énekes", "energia", "enyhe", "enyv", "eper", "épít", "épület", "ér", "érc",
    "érdek", "erdő", "erkély", "erő", "erős", "érez", "érzés", "esély", "esernyő", "eső", "est", "este", "eszköz", "eszme", "étel", "etikus", "év",
    "evez", "evező", "évszak", "ezüst", "fa", "fácán", "fagy", "fagyos", "fajta", "fakó", "fal", "falu", "falun", "fánk", "far", "fárad", "fáradt",
    "farkas", "farok", "farsang", "fatörzs", "fazék", "fedél", "fegyver", "fehér", "fej", "fejsze", "fekete", "fekvő", "fél", "feladat", "feles", "felhő",
    "felni", "felső", "félt", "féltő", "fém", "fenyő", "fény", "fényes", "fényű", "férfi", "fest", "festmény", "fésű", "fétis", "fiat", "fiatal", "fickó",
    "fiú", "fizet", "fodor", "fog", "fogas", "fogó", "fogy", "fogyó", "fóka", "fok", "fokos", "föld", "folt", "foltos", "folyó", "folyosó", "fonál",
    "fonat", "font", "fontos", "fonnyad", "forrás", "forró", "foszlik", "fő", "főnök", "főz", "friss", "fura", "furat", "furulya", "fuss", "futás",
    "futár", "fúvóka", "füge", "függ", "függöny", "fül", "füle", "fülke", "füst", "füstös", "fű", "fűz", "fűzfa", "gabona", "gácsér", "galamb", "gally",
    "garas", "gát", "gaz", "gazda", "gazdag", "gebe", "gég", "géma", "gép", "gépész", "gesztenye", "gida", "gitár", "golyó", "gomba", "gomb", "gombóc",
    "gonosz", "gond", "gondnok", "görbe", "gömb", "gödör", "gőz", "gránát", "gulya", "gumi", "gunyhó", "gyalog", "gyalul", "gyanta", "gyapjú", "gyár",
    "gyárt", "gyep", "gyerek", "gyertya", "gyermek", "gyilkos", "gyógy", "gyors", "gyomor", "gyökér", "gyöngy", "gyönyör", "győző", "gyu", "gyufa",
    "gyűrű", "hab", "habár", "habos", "had", "hadsereg", "hagyma", "haj", "hajal", "hajadon", "hajaló", "hajó", "hajnal", "hal", "halál", "hall", "halló",
    "háló", "halom", "hamu", "hang", "hangos", "hangya", "hant", "harag", "harang", "harcos", "hárem", "hárfa", "harka", "harmat", "három", "has", "hasáb",
    "hasad", "hasas", "haszon", "hát", "hatalmas", "hatalom", "határ", "hátas", "háthegy", "háto", "hátrál", "hátsó", "hattyú", "ház", "hazárd", "házas",
    "házi", "házikó", "hegedű", "hegy", "hegyes", "hely", "helyes", "hentes", "herceg", "hét", "hétköznap", "hétfő", "heti", "hév", "hévíz", "hiba",
    "hibás", "híd", "hideg", "hír", "híres", "hitel", "hit", "hitt", "hív", "hívó", "híz", "hízó", "hó", "hodály", "hódít", "hold", "holló", "homok",
    "hónap", "hord", "hordó", "horgász", "horony", "hosszú", "hóvihar", "hóvirág", "hozzá", "hő", "hős", "hőség", "hú", "húg", "hull", "hulla", "hullám",
    "hurok", "hús", "husi", "húsz", "hűt", "hűtő", "hűvös", "idő", "időjárás", "igaz", "igazság", "ígér", "ígéret", "iker", "illat", "illy", "ilyen", "ima",
    "imbolyog", "ing", "ingat", "ingatlan", "ingó", "ingovány", "inog", "inas", "ipar", "ír", "irány", "írás", "írisz", "író", "iroda", "ismer", "ismerős",
    "isza", "iszap", "ital", "ítél", "ítélet", "ív", "ível", "íves", "izom", "izzad", "izzó", "jacht", "jaj", "jámbor", "január", "jár", "járat", "járda",
    "járó", "játék", "játékos", "javas", "javasol", "jávon", "jég", "jeges", "jegy", "jegyzék", "jel", "jelen", "jelenség", "jelkép", "jelmez", "jenő",
    "jérce", "jessz", "jeti", "jó", "jobb", "jód", "jog", "joghurt", "jóslat", "jóság", "jövő", "juh", "juhász", "július", "június", "jut", "jutalom",
    "kabin", "kacag", "kacsa", "kád", "kagyló", "kajak", "kaja", "kakas", "kaland", "kalap", "kalapács", "kalács", "kalitka", "kályha", "kamat", "kamra",
    "kanál", "kandúr", "kancsó", "kanyar", "kanóc", "kapu", "kapanyél", "kapitány", "kapizsgál", "kapocs", "kapor", "káposzta", "kaptafa", "kar", "karaj",
    "karám", "karc", "kard", "karkötő", "karó", "karon", "károly", "kárpát", "kárpit", "kártya", "kaska", "kastély", "kasza", "kaszál", "katona", "kávé",
    "kavics", "kazal", "kazein", "kehely", "kék", "kele", "kelet", "kell", "kellék", "kelme", "kemény", "kémény", "ken", "kender", "kenyér", "kép",
    "képes", "képkeret", "képvisel", "kér", "kérdés", "kerék", "kerékpár", "keres", "kereszt", "keret", "kerge", "kerít", "kérlel", "kerti", "kert",
    "kertész", "kérő", "kese", "keselyű", "keserű", "kés", "kész", "készít", "kesztyű", "kév", "keve", "kevés", "kéz", "kiabál", "kiadó", "kiált",
    "kígyó", "kilométer", "kincs", "kín", "kínál", "kint", "cipelt", "király", "királynő", "kis", "kocsi", "kocka", "kód", "kofa", "kohó", "konyha",
    "kopó", "kor", "korona", "kosár", "kovács", "köd", "kő", "könyv", "kör", "körte", "kösz", "köt", "kötél", "köz", "közép", "közös", "kutya", "kürt",
    "láb", "lakás", "lakik", "lant", "lap", "lapát", "lapos", "lassú", "lát", "látvány", "láz", "leány", "lebeg", "léc", "lecke", "legyez", "légy",
    "lehet", "lejtő", "lekvár", "lélek", "lelet", "lelki", "lemez", "lencse", "lép", "lépcső", "lépés", "levél", "levegő", "levon", "liba", "lekvár",
    "likőr", "liheg", "lámpa", "láng", "lanat", "lant", "lapát", "lap", "láva", "lé", "lék", "lép", "les", "lét", "lift", "lil", "lila", "limonádé",
    "lista", "liszt", "liter", "ló", "lobog", "locsol", "lódít", "logika", "lop", "lopás", "lovag", "lovas", "lő", "lőfegyver", "lök", "lyuk", "ma",
    "maci", "mackó", "macska", "madár", "maga", "magán", "magas", "magasság", "magány", "magyar", "máj", "majom", "május", "mák", "makk", "malac",
    "malom", "málna", "mályva", "mama", "mámor", "manó", "már", "marad", "marék", "marhás", "marha", "markol", "március", "marketing", "marat", "mart",
    "más", "masa", "másik", "másod", "másol", "maszk", "matrac", "mazsola", "mécses", "meder", "medve", "meg", "még", "meggy", "meghív", "meglát",
    "megy", "megye", "méh", "meleg", "mély", "mely", "mélység", "ment", "mentő", "mény", "mér", "méret", "mérleg", "mérnök", "mese", "mesél", "mész",
    "mester", "mészáros", "méta", "metál", "metró", "metsz", "mez", "mező", "méz", "mézes", "micsoda", "mielőtt", "miért", "míg", "mígnem", "mikor",
    "mikró", "milliárd", "millió", "milyen", "minden", "mindjárt", "mindig", "miniszter", "mint", "minta", "mira", "mire", "mivel", "mocsár", "mocsok",
    "mód", "modell", "modern", "mogyoró", "moha", "móka", "mókus", "molnár", "mond", "mondat", "mondás", "morgó", "morog", "morzsa", "mos", "mosás",
    "mosoly", "most", "motor", "mozi", "mozog", "munkás", "munka", "muszáj", "mutat", "mutató", "múzeum", "mű", "műhely", "műhold", "műsor", "művész",
    "nád", "nádas", "nadrág", "nagy", "nagyapa", "nagymama", "nagyon", "nap", "naplopó", "nappal", "napraforgó", "napsugár", "narancs", "nász", "ne",
    "né", "nedv", "nedves", "négy", "négyzet", "negyed", "nehéz", "nejlon", "neked", "nekem", "nekünk", "nem", "nemes", "német", "nemzet", "nép",
    "népszerű", "név", "nevet", "nevez", "néz", "nézet", "néző", "nincs", "nóta", "növény", "nő", "nővér", "nőies", "nővérke", "nyáj", "nyál", "nyár",
    "nyárfa", "nyárs", "nyávog", "nyelv", "nyereg", "nyeremény", "nyers", "nyertes", "nyíl", "nyilat", "nyit", "nyolc", "nyolcad", "nyom", "nyomda",
    "nyomor", "nyomoz", "nyomra", "nyugodt", "nyugdíjas", "nyúl", "nyújt", "nyúlós", "ó", "oboa", "oda", "odú", "ok", "okos", "oktatás", "oldal",
    "oldat", "olló", "olaj", "olcsó", "oltár", "olvas", "olvasó", "oly", "olyan", "onnan", "opera", "óra", "óriás", "orr", "ország", "orvos", "ostor",
    "oszt", "osztály", "öt", "ötlet", "otto", "öv", "övezet", "ő", "őz", "őrizet", "őriz", "őrmester", "őrs", "őrség", "öv", "özvegy", "pados", "padló",
    "pad", "pajzs", "pakol", "palack", "palota", "pálya", "pamut", "panasz", "pánik", "pánk", "pap", "papagáj", "papír", "paplan", "papucs", "parancs",
    "paraszt", "part", "parittya", "paróka", "párol", "páros", "patak", "patika", "patkó", "páva", "pazar", "példa", "például", "péntek", "pénz",
    "perc", "peron", "pernye", "persze", "petty", "pettyes", "piac", "pihe", "pihen", "pille", "pincér", "pince", "pinty", "pipa", "pipacs", "pirít",
    "piros", "piszkos", "pizsama", "plafon", "plüss", "pocsék", "pofon", "pohár", "pók", "polc", "polgár", "póló", "pont", "pontos", "por", "poros",
    "posta", "pótol", "pötty", "pöttyös", "préda", "prémium", "prés", "próba", "pulóver", "puska", "pult", "puszi", "rabló", "rács", "rádió", "rág",
    "rágó", "raj", "rajt", "rajz", "rajzol", "rakás", "raklap", "rakomány", "rám", "ránc", "rang", "rántotta", "ranya", "rács", "réce", "recept",
    "rédli", "reformer", "reggel", "reggeli", "régi", "régió", "regiszter", "rejt", "rejtély", "remény", "rémes", "remeték", "rend", "rendőr", "rendes",
    "repce", "repül", "repülő", "rész", "részlet", "reszeli", "réteg", "rét", "retek", "rév", "rezeg", "réz", "rézsű", "ribizli", "rigó", "rikolt",
    "ritka", "rizs", "robbant", "robog", "robot", "rohan", "roham", "rojt", "róka", "rokon", "rolli", "rom", "romos", "romantik", "rongy", "ront",
    "ropi", "ropog", "rost", "rostély", "rossz", "rost", "rovat", "rovid", "rozmár", "rozsda", "rozs", "rózsa", "rúd", "ruha", "rugó", "rút", "rüh",
    "rükverc", "sál", "saját", "sajátos", "sajátít", "sajt", "sajtó", "sakk", "sakál", "saláta", "sallang", "sámán", "sámli", "samu", "sánc", "sánta",
    "sapka", "sár", "sáros", "sarok", "sátor", "sav", "savas", "segéd", "segély", "segít", "sejt", "sekély", "selejt", "selyem", "sem", "semmi",
    "senki", "seper", "seprű", "serleg", "sertés", "séta", "sétál", "siheder", "siker", "sikátor", "sikolt", "sima", "sín", "sisak", "sivít", "skatulya",
    "smaragd", "só", "sobri", "sógor", "soha", "sohasem", "sok", "sokáig", "sonka", "sor", "sorozat", "sors", "sorompó", "sovány", "sör", "sörét",
    "sötét", "sport", "statiszta", "stégl", "stopp", "strada", "strand", "suhan", "súly", "súlyos", "sumi", "sunnyog", "sűrű", "süt", "sütemény",
    "sütő", "szabad", "száj", "szak", "szakas", "szalad", "szalag", "száll", "szállás", "szalma", "szalonna", "szám", "szamár", "számos", "számít",
    "szán", "szánkó", "szánt", "szappan", "szár", "szárny", "szarv", "szarvas", "száz", "század", "szégyen", "szék", "szekér", "szekrény", "szél",
    "széle", "széles", "szélső", "szem", "személy", "szemét", "szén", "széna", "szent", "szép", "szer", "szerda", "szerelem", "szerep", "szerszám",
    "szerv", "szeret", "szervez", "szerző", "szesz", "szét", "szia", "sziget", "szíj", "szik", "szika", "szikla", "szín", "színes", "színház", "szint",
    "szív", "szivacs", "szivárvány", "szivar", "szó", "szoba", "szobor", "szódás", "szokás", "szoknya", "szonett", "szomjas", "szomorú", "szomszéd",
    "szopik", "szorgos", "szoros", "szórt", "szorult", "sző", "szög", "szöglet", "szőke", "szőlő", "szőnyeg", "szőr", "szörp", "szörny", "szú",
    "szúnyog", "szurok", "szúr", "szusz", "szűk", "szüle", "szülő", "szűz", "tábla", "tabló", "tábortűz", "tag", "tágas", "táj", "takar", "takarék",
    "takarító", "talaj", "talál", "talány", "talp", "tálca", "tálka", "tál", "támad", "tanácsos", "tanár", "tanács", "tanít", "tanonc", "tanyasi",
    "tanya", "tanú", "tapos", "tapéta", "tapint", "tapsol", "tár", "tarabs", "tárca", "tárgy", "tarka", "tarló", "társ", "tarsoly", "tart", "tartalom",
    "tartás", "táska", "tata", "tátog", "tavasz", "táv", "távol", "tea", "teás", "tege", "tegnap", "tehát", "teher", "tehén", "tej", "tejes", "tejföl",
    "tejszín", "tekint", "teknős", "télen", "teljes", "téma", "tömör", "tő", "tőr", "tőzsde", "tragikus", "trakta", "tréfás", "troll", "trombit",
    "trón", "trópusi", "trukk", "tubus", "tud", "tudomány", "tudos", "tudor", "tufa", "tükör", "túl", "túlzás", "tulipán", "tumult", "tunes", "turista",
    "túr", "túró", "tusa", "tusol", "tyúk", "tű", "tűz", "tűzoltó", "tűzhely", "tüdő", "tülök", "tünet", "türelem", "tükör", "tüskés", "tüske",
    "tüzes", "udvar", "úgy", "ujj", "új", "újság", "újra", "úszik", "út", "utca", "utaz", "utas", "után", "utolsó", "üdítő", "ügy", "ügyes", "ügyvéd",
    "ünnep", "úr", "ürge", "üst", "üveg", "üzen", "üzlet", "üt", "vacsora", "vad", "vadász", "vág", "vágat", "vagon", "vaj", "vajon", "vagy", "vagyon",
    "vágó", "vak", "váll", "vallás", "vált", "válság", "váltó", "vályú", "vám", "vámos", "van", "vándor", "vár", "varangy", "várandós", "város",
    "vas", "vasal", "vasárnap", "vásár", "vastag", "vatta", "váz", "váza", "védi", "vég", "vékony", "vél", "vele", "vélemény", "velünk", "vendég",
    "vér", "veréb", "vers", "veres", "vezér", "vezető", "vezet", "viasz", "vicc", "vidám", "vidék", "vihar", "világ", "villám", "villany", "vincze",
    "virág", "virradat", "visz", "vitás", "víz", "vizes", "vó", "vő", "vödör", "völgy", "vonal", "vonat", "vonzó", "vörös", "vulkán", "zabszem",
    "zab", "zaj", "zajos", "zálog", "zár", "zárd", "zárlat", "záró", "zászló", "zaton", "zátony", "zavar", "zene", "zenés", "zeng", "zéró", "zivatar",
    "zöld", "zömök", "zörgés", "zörög", "zseb", "zsemle", "zsidó", "zsír", "zsivány", "zsoltár", "zsömle", "zsufa", "zug", "zuhan", "zúgás", "zúg",
    "abrosz", "adag", "adó", "alak", "alany", "alap", "alkat", "alkony", "allomás", "almás", "alsó", "által", "ámbra", "amíg", "amin", "amiről",
    "ami", "amikor", "amíg", "annak", "anno", "antik", "anyám", "apám", "aprító", "apró", "aranyos", "aranyat", "arány", "arányos", "arasz", "árboc",
    "arcát", "árenda", "árok", "árus", "ásó", "atal", "atárs", "atya", "atyám", "augusztus", "avagy", "azalatt", "azaz", "azért", "azonos", "azon",
    "azután", "ázott", "babos", "badar", "bagoly", "baj", "bajos", "bajusz", "balos", "balra", "bánya", "bányász", "bár", "baraka", "barátom",
    "barom", "bástyán", "be", "beadás", "becs", "belül", "bence", "benne", "bennünk", "berak", "bérel", "bérlet", "beteg", "beton", "beutal",
    "bevonat", "bika", "bimbó", "birtok", "biztos", "blézer", "boci", "bocskor", "bódé", "bodzás", "bógáncs", "bojtos", "bokros", "boldogul",
    "bolond", "boltív", "bomba", "borász", "boros", "ború", "borul", "bőgés", "böjt", "bőven"
];
